---
default_stages: [pre-commit]
repos:
    # Black for Python formatting
    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
    # Prettier for HTML, CSS, JS formatting
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0
      hooks:
          - id: prettier
            types_or: [javascript, css, html]
            additional_dependencies:
                - prettier@3.0.0
