name: Build & Deploy

on:
    workflow_run:
        workflows:
            - Run Tests # Name of the test workflow in test.yml
        types:
            - completed

jobs:
    apply-database-migrations:
        # Ensure tests passed
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        environment: Demo

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Apply database migrations
              env:
                  DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
              run: flask db upgrade

    build-and-deploy:
        # Ensure tests passed
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
        runs-on: ubuntu-latest
        environment: Demo

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install CapRover
              run: npm install -g caprover

            - name: Login w/ CapRover
              run: caprover login -u "${{ secrets.CAPROVER_SERVER }}" -p "${{ secrets.CAPROVER_PW }}" -n my_machine

            - name: Create tar file
              run: tar -cvf deploy.tar ./*

            # Try to deploy the app within 5 minutes, otherwise fail to avoid holding the queue
            - name: Deploy the tar file
              run: timeout 300 caprover deploy -n my_machine -a "${{ secrets.CAPROVER_APP_NAME }}" -t  ${{ github.workspace }}/deploy.tar -p "${{ secrets.CAPROVER_PW }}"
