name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: Test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              env:
                  APP_NAME: Base SaaS
                  TIMEZONE: US/Eastern
                  FLASK_DEBUG: True
                  DATABASE_SECRET_KEY: 12345678901234567
                  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
                  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                  S3_KEY: ${{ secrets.S3_KEY }}
                  S3_SECRET: ${{ secrets.S3_SECRET }}
                  MAIL_FROM: webmaster@cansin.net
                  MAIL_SERVER: smtp.yandex.com
                  MAIL_PORT: 465
                  MAIL_USE_TLS: False
                  MAIL_USE_SSL: True
                  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
                  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
                  MAIL_DEBUG: False
                  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
                  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
                  STRIPE_PRODUCT_ID_FOR_CREDITS: ${{ secrets.STRIPE_PRODUCT_ID_FOR_CREDITS }}
                  STRIPE_CREDIT_UNIT_COST: ${{ secrets.STRIPE_CREDIT_UNIT_COST }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  FLASK_RUN_CERT: .devcontainer/ssl/cert.pem
                  FLASK_RUN_KEY: .devcontainer/ssl/key.pem

              run: pytest
